// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250628202952_NewProduct")]
    partial class NewProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Apple Phone",
                            ImageUrl = "1.jpg",
                            IsActive = true,
                            Name = "Iphone 15",
                            Price = 800m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Description = "Apple Phone",
                            ImageUrl = "2.jpg",
                            IsActive = true,
                            Name = "Iphone 16",
                            Price = 900m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 3,
                            Description = "Apple Phone",
                            ImageUrl = "3.jpg",
                            IsActive = true,
                            Name = "Iphone 15 Pro",
                            Price = 850m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 4,
                            Description = "Apple Phone",
                            ImageUrl = "4.jpg",
                            IsActive = true,
                            Name = "Iphone 16 Pro",
                            Price = 950m,
                            Stock = 250
                        },
                        new
                        {
                            Id = 5,
                            Description = "Apple Phone",
                            ImageUrl = "4.jpg",
                            IsActive = true,
                            Name = "Iphone 17 Pro",
                            Price = 1220m,
                            Stock = 250
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
