// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Iphone 15 Description",
                            ImageUrl = "Iphone1.jpg",
                            IsActive = true,
                            Name = "Iphone 15",
                            Price = 12.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 2,
                            Description = "Iphone 16 Description",
                            ImageUrl = "Iphone2.jpg",
                            IsActive = true,
                            Name = "Iphone 16",
                            Price = 15.99m,
                            Stock = 13
                        },
                        new
                        {
                            Id = 3,
                            Description = "Iphone 16 Pro Max Description",
                            ImageUrl = "Iphone3.jpg",
                            IsActive = true,
                            Name = "Iphone 16 Pro Max",
                            Price = 18.99m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 4,
                            Description = "Iphone 16 Pro Description",
                            ImageUrl = "Iphone4.jpg",
                            IsActive = true,
                            Name = "Iphone 16 Pro",
                            Price = 19.99m,
                            Stock = 18
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
